services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/NEXTGEN-HR
  ai-services:
    build: ./ai-services
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/NEXTGEN-HR

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ai-services

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    name: NextGen-HR
    driver: bridge
