services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/NEXTGEN-HR

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    name: NextGen-HR
    driver: bridge
